services:
  - type: web
    name: flashcard-frenzy-multiplayer
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: node server.js
    regions:
      - oregon
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: NEXT_PUBLIC_MAX_PLAYERS_PER_ROOM
        value: "8"
      - key: NEXT_PUBLIC_DEFAULT_QUESTION_TIME
        value: "30"
      - key: NEXT_PUBLIC_DEFAULT_ROUNDS
        value: "10"
      - key: NODE_ENV
        value: "production"
